### ISSUE TITLE
The no version flag doesn't work when I have set the `check_version` value to true in the config file

### ISSUE THREAD

**Issue by 0x61nas** [orhun/halp#64]
**Describe the bug**
The `--no-version` flag doesn't do anything  when I use it

**To reproduce**
1. Run with `--no-version` argument
2. The program checks for the version info

**Expected behavior**
Halp doesn't should to check for the version info when I use the `--no-version` argument

**Screenshots / Logs**
![image](https://github.com/orhun/halp/assets/44965145/f06c6859-0394-4465-a5db-19c83c659313)

**Software information**
- Operating system: Arch GNU/Linux legion 6.3.8-zen1-1-zen  ZEN SMP PREEMPT_DYNAMIC Wed, 14 Jun 2023 20:10:15 +0000 x86_64
- Rust version: rustc 1.72.0-nightly (dd5d7c729 2023-06-02)
- Project version: halp 0.1.7

**Additional context**
- The same issue with `--no-help` flag #63

**Comment by anas-elgarhy** [comment]
hmm, I don't understand how is that possible, I installed `halp` from pacman
[![asciicast](https://asciinema.org/a/593927.svg)](https://asciinema.org/a/593927)

**Comment by orhun** [comment]
Very weird, I also installed it via pacman and don't have this issue 🤔

**Comment by orhun** [comment]
![rec_20230629T172700](https://github.com/orhun/halp/assets/24392180/4242fba9-252b-4e3d-aab5-75881e3e6ce1)

**Comment by anas-elgarhy** [comment]
I think I get it, I have a config file, and as I mentioned in #61 the config will override the arguments

**Comment by anas-elgarhy** [comment]
the `--no-version` and `--no-help` flags works just fine after I deleted the config file that contains
```toml
check_version = true
check_help = true
check = [["-v", "-V", "--version"], ["-h", "--help", "help", "-H"]]
man_command = "man"
pager_command = "less -R"
cheat_sh_url = "https://cheat.sh"
```
